@startuml

[*] --> off : Car is started

off: CC is off
off --> on : On/Off
off --> off : Set/Accel
off --> off : Res/Coast
off --> off : Cancel

on: CC is turned on but\nnot controlling vehicle;\nno previous speed
on --> off : On/Off
on --> active : Set/Accel
on --> on : Res/Coast
on --> on : Cancel

inactive: CC is turned on but\nnot controlling vehicle;\nhas previous speed
inactive --> off : On/Off
inactive --> active : Set/Accel
inactive --> active : Res/Coast
inactive --> inactive : Cancel

active: CC is controlling vehicle
active --> off : On/Off
active --> active : Set/Accel
active --> active : Res/Coast
active --> inactive : Cancel

@enduml
